#! /bin/sh
xrandr --output LVDS-1 --off
xinput float 13

xsetroot -solid black

"$HOME"/.config/polybar/launch.sh &

sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width        2
bspc config window_gap          1
bspc config top_padding         18

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^3' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

termite &
termite &
